# Generated by Django 3.1.4 on 2020-12-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audible',
            name='page',
            field=models.CharField(max_length=4),
        ),
    ]
