# Generated by Django 3.1.4 on 2021-01-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_audible_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='audible',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
